config/routes.rb
Rails.application.routes.draw do
  resources :gifts
  root to: 'visitors#index'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
end

app/models/gift.rb
class Gift < ActiveRecord::Base
  has_many :ideas
  has_many :users, through: :ideas
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  belongs_to :user
  belongs_to :gift

  acts_as_taggable
  acts_as_taggable_on :recipient
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, if: :new_record?

  has_many :ideas
  has_many :gifts, through: :ideas

  def set_default_role
    if User.count == 0
      self.role ||= :admin
    else
      self.role ||= :user
    end
  end

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      if auth['info']
        user.name = auth['info']['name'] || ""
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :correct_user?

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  rescue
    nil
  end

  def user_signed_in?
    return true if current_user.present?
  end

  def correct_user?
    @user = User.find(params[:id])
    return if current_user == @user
    redirect_to root_url, alert: "Access denied."
  end

  def authenticate_user!
    return if current_user.present?
    redirect_to root_url, alert: 'You need to sign in for access to this page.'
  end
end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
  expose(:gift, attributes: :gift_params)
  expose(:gifts) { current_user.gifts }
  expose(:user) { current_user }

  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    gift.users << current_user
    if gift.save
      redirect_to gift, notice: 'Gift was successfully created.'
    else
      render :new
    end
  end

  def update
    if gift.update(gift_params)
      redirect_to gift, notice: 'Gift was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    gift.destroy
    redirect_to gifts_url, notice: 'Gift was successfully destroyed.'
  end

  private

  def gift_params
    params.require(:gift).permit(:name, :price, :description, :user_id, :image)
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  def idea_params
    params.require(:idea).permit(:user_id, :gift_id, :tag_list)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to '/auth/google_oauth2'
  end

  def create
    auth = request.env["omniauth.auth"]
    user = User.where(:provider => auth['provider'],
                      :uid => auth['uid'].to_s).first || User.create_with_omniauth(auth)
    reset_session
    session[:user_id] = user.id
    redirect_to root_url, :notice => 'Signed in!'
  end

  def destroy
    reset_session
    redirect_to root_url, :notice => 'Signed out!'
  end

  def failure
    redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  expose(:gifts) { user_signed_in? ? current_user.gifts : [] }
  expose(:user) { current_user }
  expose(:ideas) { user_signed_in? ? current_user.ideas : [] }
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/gifts/_form.html.haml
= simple_form_for(gift) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :price
    = f.input :description
    = f.input :image, label: 'Image path', placeholder: 'http://image_path.com'

  .form-actions
    = f.button :submit

app/views/gifts/edit.html.haml
%h1 Editing gift

= render 'form'

= link_to 'Show', gift
\|
= link_to 'Back', gifts_path

app/views/gifts/index.html.haml
%h1 Listing gifts

%table
  %thead
    %tr
      %th Name
      %th Price
      %th Description
      %th User
      %th
      %th
      %th

  %tbody
    - gifts.each do |gift|
      %tr
        %td= gift.name
        %td= gift.price
        %td= gift.description
        %td= user
        %td= link_to 'Show', gift
        %td= link_to 'Edit', edit_gift_path(gift)
        %td= link_to 'Destroy', gift, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Gift', new_gift_path

app/views/gifts/new.html.haml
%h1 New gift

= render 'form'

= link_to 'Back', gifts_path

app/views/gifts/show.html.haml
%p#notice= notice

%a{ href: "#"}
  %img.img-responsive{:alt => "", :src => "#{gift.image}"}
%p
  %b Name:
  = gift.name
%p
  %b Price:
  = gift.price
%p
  %b Description:
  = gift.description

= link_to 'Edit', edit_gift_path(gift)
\|
= link_to 'Back', gifts_path

app/views/layouts/_messages.html.haml
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_nav_links_for_auth.html.haml
- if user_signed_in?
  %li= link_to 'Sign out', signout_path
- else
  %li= link_to 'Sign in', signin_path

app/views/layouts/_navigation.html.haml
/ navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'
        = render 'layouts/nav_links_for_auth'

app/views/layouts/_navigation_links.html.haml
/ add navigation links to this file

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Mygifts'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Mygifts'}"}
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield

app/views/visitors/index.html.haml
.container
    .row
        .col-lg-12
            %h1
                .page-header Your Gifts
                %small Secondary Text
    - gifts.each_slice(3) do |gifts_slice|
        .row
            - gifts_slice.each do |gift|
                .col-md-4.portfolio-item
                    %a{ href: "#"}
                        %img.img-responsive{:alt => "", :src => "#{gift.image}"}
                    %h3
                        =link_to gift.name, gift_path(gift)
                    %p= "#{gift.price} pln"
                    %p= gift.description
                    %p
                        - ideas.find_by(gift: gift).recipient_list.each do |recipient|
                            %span.badge= recipient

    %hr

    .row.text-center
        .col-lg-12
            %ul.pagination
                %li
                    %a{ href: "#"} &laquo;
                %li.active
                    %a{ href: "#"}1
                %li
                    %a{ href: "#"}2
                %li
                    %a{ href: "#"}3
                %li
                    %a{ href: "#"}4
                %li
                    %a{ href: "#"}5
                %li
                    %a{ href: "#"} &raquo;
    %hr

    %footer
        .row
            .col-lg-12
                %p Copyright &copy; MyGifts 2015